# Generated by Django 6.0.5 on 2026-05-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Dokter Hewan')),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('spesialisasi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('Pakan', 'Pakan'), ('Obat & Vaksin', 'Obat & Vaksin'), ('Gaji', 'Gaji'), ('Operasional', 'Operasional'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('deskripsi', models.CharField(max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah (Rp)')),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sapi', models.CharField(max_length=20, unique=True, verbose_name='ID Sapi')),
                ('nama_sapi', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Jantan', 'Jantan'), ('Betina', 'Betina')], max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('berat_badan', models.DecimalField(decimal_places=2, help_text='Dalam Kilogram', max_digits=8)),
                ('status', models.CharField(choices=[('Hidup/Sehat', 'Hidup/Sehat'), ('Sakit', 'Sakit'), ('Dijual', 'Dijual'), ('Mati', 'Mati')], default='Hidup/Sehat', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_masuk', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_masuk'],
            },
        ),
        migrations.CreateModel(
            name='Pemeliharaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_pakan', models.CharField(max_length=100)),
                ('jumlah_pakan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biaya_pakan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Biaya (Rp)')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('sapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pakan', to='peternakan.sapi')),
            ],
        ),
        migrations.CreateModel(
            name='Panen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_produksi', models.CharField(choices=[('Susu', 'Susu'), ('Pupuk Kandang', 'Pupuk Kandang'), ('Anak Sapi', 'Anak Sapi'), ('Penjualan Sapi Dewasa', 'Penjualan Sapi Dewasa')], max_length=25)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('satuan', models.CharField(default='Liter', max_length=10)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Jual per Satuan (Rp)')),
                ('sapi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_panen', to='peternakan.sapi')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('diagnosa', models.TextField()),
                ('tindakan', models.TextField(blank=True, null=True)),
                ('resep_obat', models.TextField(blank=True, null=True)),
                ('biaya_konsultasi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('update_status_sapi', models.CharField(choices=[('Hidup/Sehat', 'Hidup/Sehat'), ('Sakit', 'Sakit'), ('Dijual', 'Dijual'), ('Mati', 'Mati')], default='Hidup/Sehat', help_text='Otomatis mengubah status sapi', max_length=15)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_medis', to='peternakan.dokter')),
                ('sapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_medis', to='peternakan.sapi')),
            ],
        ),
    ]
