# Generated by Django 6.0.5 on 2026-05-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peternakan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapi',
            name='rumpun',
            field=models.CharField(choices=[('Limousin', 'Limousin'), ('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Ongole', 'Ongole'), ('Bali', 'Bali'), ('Madura', 'Madura'), ('Holstein', 'Holstein (Frisian)'), ('POH', 'Peranakan Ongole Hilang'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=20, verbose_name='Rumpun/Breed'),
        ),
        migrations.AddField(
            model_name='sapi',
            name='tinggi_sapi',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tinggi gumba/pundak dalam cm', max_digits=5, null=True, verbose_name='Tinggi (cm)'),
        ),
    ]
