# Generated by Django 6.0.5 on 2026-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peternakan', '0002_sapi_rumpun_sapi_tinggi_sapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisi',
            name='berat_sapi_saat_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Berat Sapi Saat Ini (Kg)'),
        ),
        migrations.AddField(
            model_name='supervisi',
            name='update_tinggi_sapi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Update Tinggi Sapi (Cm)'),
        ),
        migrations.AlterField(
            model_name='sapi',
            name='rumpun',
            field=models.CharField(choices=[('Limousin', 'Limousin'), ('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Ongole', 'Ongole'), ('Bali', 'Bali'), ('Madura', 'Madura'), ('Holstein', 'Holstein (Frisian)'), ('POH', 'Peranakan Ongole Hilang'), ('PO', 'PO'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=20, verbose_name='Rumpun/Breed'),
        ),
    ]
