# Generated by Django 6.0.5 on 2026-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peternakan', '0003_supervisi_berat_sapi_saat_ini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisi',
            name='bukti_kuitansi',
            field=models.ImageField(blank=True, null=True, upload_to='images/kuitansi/', verbose_name='Bukti Kuitansi/Tindakan'),
        ),
        migrations.AlterField(
            model_name='supervisi',
            name='berat_sapi_saat_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supervisi',
            name='update_status_sapi',
            field=models.CharField(choices=[('Hidup/Sehat', 'Hidup/Sehat'), ('Sakit', 'Sakit'), ('Dijual', 'Dijual'), ('Mati', 'Mati')], default='Hidup/Sehat', max_length=15),
        ),
        migrations.AlterField(
            model_name='supervisi',
            name='update_tinggi_sapi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
